### ISSUE TITLE
Cannot render email templates without a template engine

### ISSUE THREAD

**Issue by Effzz** [Tagada216/adonisjs-boilerplate#2]
I tried to register using email, but I encountered the following error:

> RuntimeException: Cannot render email templates without a template engine
>     at getTemplateEngine (/my-api/node_modules/@adonisjs/mail/src/message.ts:50:15)
>     at computeContentsFor (/my-api/node_modules/@adonisjs/mail/src/message.ts:88:28)
>     at sendCompiled (/my-api/node_modules/@adonisjs/mail/src/mailer.ts:95:19)
>     at Mailer.send (/my-api/node_modules/@adonisjs/mail/src/mailer.ts:179:17)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at Function.sendUserActivationEmail (/my-api/app/services/email/email_services.ts:9:9)
>     at AuthService.sendActivationEmail (/my-api/app/services/auth/auth_services.ts:29:9)
>     at AuthService.register (/my-api/app/services/auth/auth_services.ts:37:13)
>     at AuthController.register (/my-api/app/controllers/auth/auth_controller.ts:12:51) {
>   status: 500,
>   code: 'E_RUNTIME_EXCEPTION'

It seems like Edge is not being recognized as the email template view engine.

**Comment by Effzz** [comment]
sorry my bad, I just do 

> node ace add edge

and everything works

**Comment by Effzz** [comment]
solved
